languages = {
    'pt': {'language': "Portuguese",
            'word_classes': ["Noun", "Verb", "Adjective", "Pronoun", "Article",
                "Contraction", "Preposition", "Proverb", "Proper noun",
                "Adverb", "Conjunction", "Numeral", "Interjection", "Symbol", "Suffix", "Prefix"],
            'start-urls_1': ["https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/a",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/b",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/c",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/d",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/e"],
            'start-urls_2': ["https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/f",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/g",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/h",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/i",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/j"],
            'start-urls_3': ["https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/k",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/l",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/m",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/n",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/o"],
            'start-urls_4': ["https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/p",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/q",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/r",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/s",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/t"],
            'start-urls_5': ["https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/u",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/v",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/w",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/x",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/y",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/z",],
        },
    'es': {'language': "Spanish", 
            'word_classes': ["Noun", "Verb", "Adjective", "Pronoun", "Article",
                "Contraction", "Preposition", "Proverb", "Proper noun",
                "Adverb", "Conjunction", "Numeral", "Interjection", "Symbol", "Suffix", "Prefix"],
            'start-urls_1': ["https://en.wiktionary.org/wiki/Appendix:Index/Spanish/a",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/b",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/c",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/d",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/e"],
            'start-urls_2': ["https://en.wiktionary.org/wiki/Appendix:Index/Spanish/f",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/g",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/h",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/i",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/j"],
            'start-urls_3': ["https://en.wiktionary.org/wiki/Appendix:Index/Spanish/k",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/l",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/m",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/n",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/ñ"],
            'start-urls_4': ["https://en.wiktionary.org/wiki/Appendix:Index/Spanish/o",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/p",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/q",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/r",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/s"],
            'start-urls_5': ["https://en.wiktionary.org/wiki/Appendix:Index/Spanish/t",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/u",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/v",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/w",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/x",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/y",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Spanish/z"],
        },
    'fr': {'language': "French", 
            'word_classes': ["Noun", "Verb", "Adjective", "Pronoun", "Article",
                "Contraction", "Preposition", "Proverb", "Proper noun",
                "Adverb", "Conjunction", "Numeral", "Interjection", "Symbol", "Suffix", "Prefix"],
            'start-urls_1': ["https://en.wiktionary.org/wiki/Appendix:Index/French/a",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/b",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/c",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/d",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/e"],
            'start-urls_2': ["https://en.wiktionary.org/wiki/Appendix:Index/French/f",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/g",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/h",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/i",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/j"],
            'start-urls_3': ["https://en.wiktionary.org/wiki/Appendix:Index/French/k",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/l",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/m",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/n",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/o"],
            'start-urls_4': ["https://en.wiktionary.org/wiki/Appendix:Index/French/p",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/q",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/r",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/s",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/t"],
            'start-urls_5': ["https://en.wiktionary.org/wiki/Appendix:Index/French/u",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/v",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/w",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/x",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/y",
                            "https://en.wiktionary.org/wiki/Appendix:Index/French/z",],
        },
    'de': {'language': 'German',
            'word_class': ["Noun", "Verb", "Adjective", "Pronoun", "Article",
                "Contraction", "Preposition", "Proverb", "Proper noun",
                "Adverb", "Conjunction", "Numeral", "Interjection", "Symbol", "Suffix", "Prefix"],
            'start-urls_1': ["https://en.wiktionary.org/wiki/Appendix:Index/German/a",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/b",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/c",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/d",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/e"],
            'start-urls_2': ["https://en.wiktionary.org/wiki/Appendix:Index/German/f",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/g",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/h",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/i",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/j"],
            'start-urls_3': ["https://en.wiktionary.org/wiki/Appendix:Index/German/k",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/l",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/m",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/n",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/o"],
            'start-urls_4': ["https://en.wiktionary.org/wiki/Appendix:Index/German/p",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/q",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/r",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/s",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/t"],
            'start-urls_5': ["https://en.wiktionary.org/wiki/Appendix:Index/German/u",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/v",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/w",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/x",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/y",
                            "https://en.wiktionary.org/wiki/Appendix:Index/German/z",],
        },
    'it': {'language': "Italian",
            'word_classes': ["Noun", "Verb", "Adjective", "Pronoun", "Article",
                "Contraction", "Preposition", "Proverb", "Proper noun",
                "Adverb", "Conjunction", "Numeral", "Interjection", "Symbol", "Suffix", "Prefix"],
            'start-urls_1': ["https://en.wiktionary.org/wiki/Appendix:Index/Italian/a",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/b",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/c",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/d",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/e"],
            'start-urls_2': ["https://en.wiktionary.org/wiki/Appendix:Index/Italian/f",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/g",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/h",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/i",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/j"],
            'start-urls_3': ["https://en.wiktionary.org/wiki/Appendix:Index/Italian/k",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/l",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/m",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/n",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/o"],
            'start-urls_4': ["https://en.wiktionary.org/wiki/Appendix:Index/Italian/p",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/q",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/r",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/s",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/t"],
            'start-urls_5': ["https://en.wiktionary.org/wiki/Appendix:Index/Italian/u",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/v",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/w",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/x",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/y",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Italian/z",],
        },
    'ru': {'language': "Russian",
            'word_classes': ["Noun", "Verb", "Adjective", "Pronoun", "Article",
                "Contraction", "Preposition", "Proverb", "Proper noun",
                "Adverb", "Conjunction", "Numeral", "Interjection", "Symbol", "Suffix", "Prefix"],
            'start-urls_1': ["https://en.wiktionary.org/wiki/Appendix:Index/Russian/а",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/б",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/в",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/г",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/д",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/е"],
            'start-urls_2': ["https://en.wiktionary.org/wiki/Appendix:Index/Russian/ж",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/з",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/и",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/й",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/к"],
            'start-urls_3': ["https://en.wiktionary.org/wiki/Appendix:Index/Russian/л",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/м",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/н",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/о",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/п"],
            'start-urls_4': ["https://en.wiktionary.org/wiki/Appendix:Index/Russian/р",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/с",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/т",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/у",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/ф"],
            'start-urls_5': ["https://en.wiktionary.org/wiki/Appendix:Index/Russian/х",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/ц",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/ч",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/ш",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/щ"],
            'start-urls_6': ["https://en.wiktionary.org/wiki/Appendix:Index/Russian/ъ",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/ы",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/ь",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/э",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/ю"],
            'start-urls_7': ["https://en.wiktionary.org/wiki/Appendix:Index/Russian/я",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Russian/0"],
        },
    'pl': {'language': "Polish",
            'word_classes': ["Noun", "Verb", "Adjective", "Pronoun", "Article",
                "Contraction", "Preposition", "Proverb", "Proper noun",
                "Adverb", "Conjunction", "Numeral", "Interjection", "Symbol", "Suffix", "Prefix"],
            'start-urls_1': ["https://en.wiktionary.org/wiki/Appendix:Index/Polish/a",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/ą",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/b",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/c",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/ć"],
            'start-urls_2': ["https://en.wiktionary.org/wiki/Appendix:Index/Polish/d",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/e",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/ę",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/f",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/g"],
            'start-urls_3': ["https://en.wiktionary.org/wiki/Appendix:Index/Polish/h",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/i",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/j",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/k",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/l"],
            'start-urls_4': ["https://en.wiktionary.org/wiki/Appendix:Index/Polish/ł",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/m",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/n",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/ń",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/o"],
            'start-urls_5': ["https://en.wiktionary.org/wiki/Appendix:Index/Polish/ó",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/p",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/r",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/s",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/ś"],
            'start-urls_6': ["https://en.wiktionary.org/wiki/Appendix:Index/Polish/t",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/u",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/w",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/y",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/z"],
            'start-urls_7': ["https://en.wiktionary.org/wiki/Appendix:Index/Polish/ź",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Polish/ż"],
        },
    }