languages = {
    'pt': {'language': "Portuguese",
            'word_classes': ["Phrase", "Noun", "Verb", "Adjective", "Pronoun", "Article",
                "Contraction", "Preposition", "Proverb", "Proper noun",
                "Adverb", "Conjunction", "Numeral", "Interjection", "Symbol", "Suffix", "Prefix"],
            'start-url-crawler': ['https://en.wiktionary.org/wiki/Category:Portuguese_language'],
       },
    'es': {'language': "Spanish", 
            'word_classes': ["Phrase", "Noun", "Verb", "Adjective", "Pronoun", "Article",
                "Contraction", "Preposition", "Proverb", "Proper noun",
                "Adverb", "Conjunction", "Numeral", "Interjection", "Symbol", "Suffix", "Prefix"],
            'start-url-crawler': ['https://en.wiktionary.org/wiki/Category:Spanish_language'], 
        },
    'fr': {'language': "French", 
            'word_classes': ["Phrase", "Noun", "Verb", "Adjective", "Pronoun", "Article",
                "Contraction", "Preposition", "Proverb", "Proper noun",
                "Adverb", "Conjunction", "Numeral", "Interjection", "Symbol", "Suffix", "Prefix"],
            'start-url-crawler': ['https://en.wiktionary.org/wiki/Category:French_language'], 
        },
    'de': {'language': 'German',
            'word_class': ["Noun", "Verb", "Adjective", "Pronoun", "Article",
                "Contraction", "Preposition", "Proverb", "Proper noun",
                "Adverb", "Conjunction", "Numeral", "Interjection", "Symbol", "Suffix", "Prefix"],
            'start-url-crawler': ['https://en.wiktionary.org/wiki/Category:German_language'], 
        },
    'it': {'language': "Italian",
            'word_classes': ["Phrase", "Noun", "Verb", "Adjective", "Pronoun", "Article",
                "Contraction", "Preposition", "Proverb", "Proper noun",
                "Adverb", "Conjunction", "Numeral", "Interjection", "Symbol", "Suffix", "Prefix"],
            'start-url-crawler': ['https://en.wiktionary.org/wiki/Category:Italian_language'], 
        },
    'ru': {'language': "Russian",
            'word_classes': ["Phrase", "Noun", "Verb", "Adjective", "Pronoun", "Article",
                "Contraction", "Preposition", "Proverb", "Proper noun",
                "Adverb", "Conjunction", "Numeral", "Interjection", "Symbol", "Suffix", "Prefix"],
            'start-url-crawler': ['https://en.wiktionary.org/wiki/Category:Russian_language'], 
        },
    'pl': {'language': "Polish",
            'word_classes': ["Phrase", "Noun", "Verb", "Adjective", "Pronoun", "Article",
                "Contraction", "Preposition", "Proverb", "Proper noun",
                "Adverb", "Conjunction", "Numeral", "Interjection", "Symbol", "Suffix", "Prefix"],
            'start-url-crawler': ['https://en.wiktionary.org/wiki/Category:Polish_language'], 
        },
    }