languages = {
    'pt': {'language': "Portuguese",
            'word_classes': ["Noun", "Verb", "Adjective", "Pronoun", "Article",
                "Contraction", "Preposition", "Proverb", "Proper noun",
                "Adverb", "Conjunction", "Numeral", "Interjection", "Symbol"],
            'start-urls_1': ["https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/a",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/b",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/c",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/d",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/e"],
            'start-urls_2': ["https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/f",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/g",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/h",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/i",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/j"],
            'start-urls_3': ["https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/k",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/l",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/m",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/n",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/o"],
            'start-urls_4': ["https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/p",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/q",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/r",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/s",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/t"],
            'start-urls_5': ["https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/w",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/x",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/y",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/z",
                            "https://en.wiktionary.org/wiki/Appendix:Index/Portuguese/t"],

        }
    }